In [ ]:
#Basics operation of a number

In [1]:
import numpy as np

In [2]:
a=np.array([10,10,10])
b=np.array([5,5,5])

In [3]:
a+b     #addition of array

array([15, 15, 15])

In [4]:
a-b     #subtraction of array

array([5, 5, 5])

In [5]:
a/b   #division of array , the default type of array is float hence we get output as float

array([2., 2., 2.])

In [7]:
a%3    #   % - modulos , gives the reminder as output

array([1, 1, 1], dtype=int32)

In [8]:
#understanding dot function or dot method.
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

In [9]:
print('A:\n',A)
print('B:\n',B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [10]:
#elementwise multilpication.
A*B              

array([[2, 0],
       [0, 4]])

In [11]:
#dot function
A.dot(B)      #matrix multiplication of rows with columns

array([[5, 4],
       [3, 4]])

In [12]:
#unary operators
ages=np.array([12,15,18,20])

In [13]:
ages.sum()    #total sum of the array

65

In [14]:
ages.max()     #max. value in the array

20

In [15]:
ages.min()      #min. value in the array

12

In [16]:
numbers=np.arange(12).reshape(3,4)

In [17]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Rows and columnwise operation.

#axis 0  represents columns
#axis 1  represents rows

In [18]:
numbers.sum(axis=0)    # column addition

array([12, 15, 18, 21])

In [19]:
numbers.sum(axis=1)   #rows addition

array([ 6, 22, 38])

In [20]:
#universal functions of numpy

#to find the mean of array.    --- mean()

test_scores=np.array([32.23,45.33,87.33,31.67,22.0])

print("the mean of the test scores is :")
print(np.mean(test_scores))

the mean of the test scores is :
43.712


In [21]:
#median of the array    --- median()

print("the median of the test scores is :")
print(np.median(test_scores))

the median of the test scores is :
32.23


In [24]:
#standard deviation      ----- std()

print("the standard deviation of the test scores is :")
print(np.std(test_scores))

the standard deviation of the test scores is :
23.0365139723874


In [25]:
 # Variance           ------ var()

print("the variance of the test scores is :")
print(np.var(test_scores))

the variance of the test scores is :
530.680976
