In [1]:
#Introduction to creating arrays
#whenever we need to use the libraries we need to import them first

import numpy as np    #here np is reference/alias name

array_one=np.array([1,2,3,4,5])

array_one

array([1, 2, 3, 4, 5])

In [2]:
type(array_one)

numpy.ndarray

In [6]:
#case 2
numbers=[9,8,7,6]

In [7]:
array_two=np.array(numbers)

array_two

array([9, 8, 7, 6])

In [9]:
#matrix array
array_of_zeros=np.zeros((3,4))   #here, zeros is the built in numpy library function
                                    #float is considered as default data type.hence in the output matrix we can see 0.,which is
                                      #  float  value
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])