In [1]:
import numpy as np

In [2]:
#ones matrix
array_ones=np.ones((3,4))
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#to have a int type matrix
array_ones_int=np.ones((3,4),dtype=np.int16)     #int16 are used to define the length of the integer ,  so as int32, int64
array_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [6]:
#empty array
array_empty=np.empty((2,3))
array_empty

array([[6.03e-322, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [8]:
#identity matrix
array_eye=np.eye(4)         #for identity matrix , only row parameter should be passed
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
#req. to print the even numbers from 1 to 20
array_even=np.arange(2,20,2)
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#  arange funtion of numpy is simillar to the range function in python , where the last number will be exclusive. 

In [10]:
#float data values
array_float=np.arange(0,2,0.3)
array_float

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [11]:
#2 dimensional array
array_2d=np.array([(2,4,6),(1,3,5)])
array_2d

array([[2, 4, 6],
       [1, 3, 5]])

In [12]:
#method to know the value of the dimension of the array
# shape method
array_2d.shape

(2, 3)

In [13]:
array_eye.shape

(4, 4)

In [16]:
#creating numbers
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [17]:
# difference of print and display array
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [18]:
a=np.arange(6)

print(a)

[0 1 2 3 4 5]


In [ ]:
#on printing the array it is same as a list excluding the array keyword,
where on displaying the array there wont be change 

In [20]:
#reshape

array_nd=np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
#when the arange function is used the matrix value is product of rows and columns
# when we are using reshape function , the paramater values should be product of rows and columns

In [21]:
array_nd=np.arange(6).reshape(4,1)

array_nd

ValueError: cannot reshape array of size 6 into shape (4,1)

In [ ]:
#in the above example, the reshape parameter is the product of defined value in the range function.