In [ ]:
#Universal function in array

In [1]:
import numpy as np

In [2]:
salary=np.genfromtxt('Salary.csv',delimiter=',')
salary

array([  6000.   ,   6700.   ,  33333.   ,  45222.   , 322555.   ,
        43325.   ,   4944.556,  86606.   , 955555.   , 488888.   ])

In [3]:
#to find the number of records in the file.
salary.shape

(10,)

In [4]:
#Applying the stastiscal operation
mean=np.mean(salary)

median=np.median(salary)

sd=np.std(salary)

var=np.var(salary)

In [5]:
#f string usgae before python 3.6

print('Mean=%i'%mean)

print('Median=%i'%median)

print('Standard deviation=%i'%sd)

print('Variance=%i'%var)

Mean=199312
Median=44273
Standard deviation=295215
Variance=87152153018


In [6]:
# Indexing and slicing of arrays
a=np.arange(11)**2     #square numbers till 11 , last value will be exclusive
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [7]:
#to access the elements using index

a[2]

4

In [8]:
a[10]

100

In [9]:
a[-1]

100

In [10]:
a[-5]

36

In [11]:
#Slicing of array
a[0:2]     #here, start and end index range is specified. and ;last value will be exclusive. 

array([0, 1], dtype=int32)

In [12]:
a[0:3]

array([0, 1, 4], dtype=int32)

In [13]:
a[3:6]

array([ 9, 16, 25], dtype=int32)

In [14]:
a[-1:-4]

array([], dtype=int32)

In [15]:
#how do we reverse a array

a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [17]:
student=np.array([['sheryas','chandra','sudha','sindhu'],
                 [20,30,40,50],
                 [77,22,3,55]])

In [18]:
student[0]     #row zero will be accessed.

array(['sheryas', 'chandra', 'sudha', 'sindhu'], dtype='<U7')

In [19]:
student[1]        #dtype='<U7'  ,  < - little indian style , U-- unicode   ,  > --- big indian style.

array(['20', '30', '40', '50'], dtype='<U7')

In [20]:
student[2]

array(['77', '22', '3', '55'], dtype='<U7')

In [21]:
student[0:2]

array([['sheryas', 'chandra', 'sudha', 'sindhu'],
       ['20', '30', '40', '50']], dtype='<U7')

In [22]:
#accessing the individual element.

student[0,2]      #here, row and column values are fed as input.

'sudha'

In [23]:
student[0,3]

'sindhu'

In [24]:
#accessing 2nd row vaules

student[1,2]

'40'